{{- if .Values.db.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phpmyadmin.fullname" . }}-db-secret
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.db.password | b64enc }}
{{- end }}
